spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 51882977262-gmpme9u0do5pn4d3aubelspl37bc1r6o.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot